name: Release Image

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version of release image'
        required: true
        default: 'latest'
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.ref_name }}

run-name: release image ${{ inputs.release_version }} ${{ github.ref_name }}

jobs:
  release-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get_relese_version.outputs.release_version }}
    steps:
      - name: Get Release Version
        id: get_relese_version
        run: |
          RELEASE_VERSION=${{ inputs.release_version }}
          if [ -z "$RELEASE_VERSION" ]; then
              RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          fi
          echo release_version=$RELEASE_VERSION >> $GITHUB_OUTPUT

  release-image:
    needs: release-version
    uses: apecloud/apecloud-cd/.github/workflows/release-image-cache.yml@v0.1.54
    with:
      IMG: "apecloud/prometheus-mssql-exporter"
      VERSION: "${{ needs.release-version.outputs.release-version }}"
      BUILDX_ARGS: "GIT_COMMIT=${{ github.sha }}"
      DOCKERFILE_PATH: "./Dockerfile"
      APECD_REF: "v0.1.54"
    secrets: inherit
